language: python
python:
  - "3.6"
#  - "3.7-dev"  Disabled as PyYAML seems to fail as of 180421 https://travis-ci.org/chrizzFTD/naming/jobs/369410602
install:
  - pip install python-coveralls
script:
  - coverage run -m unittest discover $TRAVIS_BUILD_DIR -v
after_success:
  - coveralls
